# -*- coding: utf-8 -*-
# Cut analysis. type: FIX (error/overpricing, free) | VERIFY (may vanish on evidence)
#                     SCOPE (you lose something) | DEFER (pay later) | SCHEDULE (programme-driven)
# gate: OK | CODE | SLA | ASK
C = [
# --- FIX: free money, no scope lost -----------------------------------------
("500","Toilet accessories, 30 sets @ $7,500","FIX",225_000,75_000,"OK",
 "$7,500 per set is the dev budget's own rate but it reads as a per-RESTROOM allowance, not per fixture group. 189 fixtures across ~10 restroom groups is 10 sets, not 30. Recount off the drawings."),
("500","Combine existing services","FIX",200_000,0,"OK",
 "Only needed if you are retaining and merging the old service. With a new 5,000A service from a new vault this line is redundant. Confirm with the electrical engineer."),
("500","Generator for fire pump backup","VERIFY",185_000,0,"CODE",
 "Required only where the water supply cannot support the fire pump on utility power alone. A dedicated generator may not be needed. Ask the fire protection engineer."),
("400","Decorative feature above each back bar","SCOPE",60_000,0,"OK",
 "Six decorative features at $10,000. Pure aesthetic in a room whose aesthetic is exposed structure."),
("400","CMU elevator tower at stage","SCOPE",104_195,0,"OK",
 "Second elevator tower. With one ADA car and a small BOH lift you do not need two masonry towers."),
("600","Freight & installation","FIX",375_000,250_000,"OK",
 "Carried from FT/dev budget at $375k against a bar package now less than half the size. Scale it with the equipment."),
# --- VERIFY: may vanish entirely on evidence --------------------------------
("000","Roofing felt & mastic abatement","VERIFY",555_750,0,"OK",
 "PRESUMED asbestos on a 1948 precast roof. Nobody has sampled it. An ACP-5 survey costs a few thousand and could delete this entire line. HIGHEST VALUE PER DOLLAR SPENT ON THIS SHEET."),
("100","Foundations for the new load path","ASK",1_087_650,0,"ASK",
 "Ask Rooflifters whether footings and underpinning are inside the $3-4M quote. If yes, the whole group comes out."),
("100","Roof-to-wall closure","ASK",241_643,0,"ASK",
 "Ask whether the new roof/wall joint is theirs. Their scope includes 'external metal siding to enclose the building' which may already cover it."),
("100","Fire separation between zones","VERIFY",200_000,0,"CODE",
 "The lifter's own exclusion says 'if required'. A single-volume assembly space may need none. Architect to confirm."),
("500","HVAC — repriced on load rather than area","VERIFY",5_205_550,4_100_000,"CODE",
 "The contractor priced $40/SF over 120,000 SF against a 74,100 SF building. Tonnage (400-500) looks right for 7,440 occupants but the COST basis does not. A real load calculation could take $1M+ out. Ask the mechanical engineer whether this was priced on load or on area."),
("500","Con Ed vault, conduit & feeders","VERIFY",850_000,850_000,"OK",
 "My estimate with no utility quote behind it. Could go either way by several hundred thousand. Get the Con Ed feasibility letter early — it also drives the schedule."),
("300","Mezzanine steel at 20 lb/SF","VERIFY",840_000,700_000,"CODE",
 "20 lb/SF assumes 100 psf assembly loading throughout. If part of the mezzanine is seated rather than dense standing, the design load drops and so does the tonnage. Structural engineer to confirm."),
# --- SCOPE: real cuts, you lose something -----------------------------------
("400","Acoustic panels — reduce coverage","SCOPE",1_120_000,720_000,"SLA",
 "28,000 SF of wall panel at $40. Targeted treatment on first-reflection and rear surfaces rather than blanket coverage gets most of the acoustic benefit. RISK: this is the licence-to-operate item. Do not cut without the acoustician signing off, and do not cut the isolation or flanking control."),
("400","Polished concrete to sealed concrete","SCOPE",416_000,208_000,"OK",
 "52,000 SF at $8 polished vs $4 sealed. Sealed is the Infinity aesthetic anyway and it is what most of the room will be under foot traffic."),
("400","Interior sound/fire rated walls","SCOPE",360_000,270_000,"CODE",
 "18,000 SF at $20 is my estimate of stair and shaft enclosure. Recount off the drawings — the rated area is fixed by code but my quantity is a guess."),
("600","Rent-to-buy the house PA","DEFER",2_200_000,0,"OK",
 "Defers the largest single FF&E line. NOT a saving — total cost is higher over the life of the kit. Use it for day-one cash only."),
("600","Mezzanine box chairs","SCOPE",197_100,120_000,"SLA",
 "657 chairs at $300. Fewer boxes with rail standing behind. Coordinate with the seat count counsel confirms for the classification."),
("600","Exterior building signage","SCOPE",150_000,90_000,"OK",
 "Identification and wayfinding, not a facade programme."),
("600","FF&E installation labour","SCOPE",600_000,420_000,"OK",
 "Dev budget's own $600k against an FF&E package now 16% smaller. Scale it."),
("200","VIP platforms, FOH & decking","SCOPE",278_488,200_000,"OK",
 "FT actuals for an open-air stage with a larger VIP programme. Scale to the mezzanine-based VIP here."),
# --- DEFER: pay later, no penalty -------------------------------------------
("400","Entry mats & stair treads","DEFER",32_500,0,"OK","Fit-out item, no penalty for landing later."),
("600","Merchandise cases","DEFER",26_000,0,"OK","Furniture. Buy when the merch programme is set."),
("600","Office furniture","DEFER",65_000,0,"OK","Buy at fit-out, not at buyout."),
("500","House / architectural lighting BOH","DEFER",185_000,120_000,"OK",
 "Circulation and BOH lighting to a working standard now; decorative later."),
# --- SCHEDULE: programme is the cost driver ---------------------------------
("000","Sidewalk shed rental","SCHEDULE",575_000,431_000,"OK",
 "24 months at $23,958/month. Every month of programme costs you $23,958. An 18-month shed duration saves $143,748. Sequence the lift early and strike the shed before fit-out."),
("000","Temporary heat & dehumidification","SCHEDULE",85_000,45_000,"OK",
 "Winter exposure. Sequencing the envelope closure before winter roughly halves it."),
("700","Project management","SCOPE",1_100_000,500_000,"OK",
 "ALREADY APPLIED at your instruction. Now carried at $500,000 — 1.1% of trade cost — for OUR OWN development team: Thomas as project manager plus consultants. Live Nation is the co-pro / programming partner, not the developer. This is BELOW the 2-4% norm, so it is a number to defend, not one with more room in it. It funds roughly one full-time PM for the duration plus a limited consultant bench."),
# --- THE RIGGING GRID over the crowd ----------------------------------------
("200","Access catwalk on the header lines","SCOPE",64_750,0,"OK",
 "The one soft item in the grid. Focus the rig from a genie lift between load-ins instead of walking a catwalk. Costs you crew hours on changeover, saves $64,750."),
("200","Cross-span girders — bay spacing","VERIFY",325_500,232_500,"ASK",
 "7 girders at 25ft on centre. At 35ft on centre you need 5, not 7, and save $93,000. Ask the production designer whether the house plot actually needs a pick point every 25ft, or whether 35ft plus bridles covers every plot you will really hang."),
("200","Chain hoists at grid pick points","DEFER",91_200,45_600,"OK",
 "32 motors is a full house complement. Buy 16 now, hang the rest of the points with dead-hangs, and add motors as programming demands. The STEEL is what you cannot add later; the motors you can."),
("200","Rigging grid vs. roof capacity","VERIFY",1_363_450,1_363_450,"ASK",
 "DO NOT CUT THIS TO SAVE MONEY — check it against the ROOF instead. The grid is what lets the new roof stay at 15 lb/SF. If the estimator has ALSO priced a roof rated to carry rigging, you are paying twice. Confirm the roof steel is designed to carry itself and nothing else."),
]
