# -*- coding: utf-8 -*-
# 165 Randolph — DETAILED development budget.
# division -> line -> [(sub-item, qty, unit, rate, source)]
SF=74_100; MEZZ=14_000; PERI=1_089; RISE=30; BAND=PERI*RISE; STAGE=3_500
# Rigging grid drivers. CROWDW is the clear width the grid must span across the crowd.
# 150 x 175 = 26,250 SF, which lands on the 26,000 SF floor crowd area the Wake test fit's
# own occupancy loads imply (5,200 standing x 5 SF/occ). CHANGE THESE WHEN THE TEST FIT IS CONFIRMED.
CROWDW=150; CROWDD=175; CROWDSF=CROWDW*CROWDD
XBAY=25; XN=CROWDD//XBAY; XLF=XN*CROWDW; HDRLF=2*CROWDD; TOWERS=8; HOISTS=32
D = [
("000","SITE & ENABLING",[
 ("Sidewalk shed / bridge",[
   ("Sidewalk shed, erect & dismantle",PERI,"LF",210,"NYC shed ~$180-240/LF erected"),
   ("Shed rental, 24 months",PERI*24,"LF-mo",22,"SCHEDULE-DRIVEN. Rented monthly — every month of programme costs $23,958. Reduced from 30 to 24 months; confirm against the real construction schedule"),
   ("DOT permit & renewals",1,"LS",45_000,"Sidewalk shed permit, renewed periodically"),
   ("Lighting & signage on shed",PERI,"LF",18,"Required by DOT"),
   ("Netting & debris containment",BAND,"SF",1.10,"Facade protection during the lift"),
 ]),
 ("Interior protection & containment",[
   ("Slab protection, hardboard & poly",SF,"SF",1.35,"Protecting the existing slab"),
   ("Dust partitions & negative air",1,"LS",65_000,"Containment during demo and abatement"),
   ("Protection of retained equipment",1,"LS",22_000,""),
 ]),
 ("Temporary weather protection",[
   ("Temporary roof membrane at open areas",SF*0.25,"SF",8.50,"Only ~25% of roof open at any stage on a lift"),
   ("Perimeter tarping at the lift band",BAND,"SF",3.20,""),
   ("Temporary heat & dehumidification",1,"LS",85_000,"Winter work"),
 ]),
 ("Asbestos / hazmat abatement",[
   ("ACP-5 / ACP-7 filing & asbestos investigator",1,"LS",45_000,"NYC required on a 1948 building"),
   ("Roofing felt & mastic abatement",SF,"SF",7.50,"SURVEY-DEPENDENT. PRESUMED ACM on a 1948 precast roof — nobody has sampled it. If the roof is clean this line goes to near zero. Get the ACP-5 survey done early; it is worth $555,750"),
   ("Pipe & boiler insulation abatement",1,"LS",120_000,"Dev budget notes a 5,250 MBH boiler and steam piping"),
   ("Lead paint abatement at steel",1,"LS",95_000,""),
   ("Air monitoring & clearance",1,"LS",55_000,""),
   ("Hazmat disposal & manifesting",1,"LS",130_000,""),
 ]),
 ("Demolition — interior",[
   ("Demo masonry walls at new entry/lobby",2_500,"SF",12,"Dev budget 024100-1 rate & qty"),
   ("Demo 8in CMU wall, 20ft tall",1_975,"SF",14,"Dev budget qty, unpriced"),
   ("Demo existing roll-up doors",8,"EA",1_850,"Dev budget qty"),
   ("Demo existing exterior doors",7,"EA",650,"Dev budget qty"),
   ("Demo windows 1ft x 10ft",34,"EA",12,"Dev budget 024100 rate & qty"),
   ("Demo ceiling-mount steam heaters & piping",28,"EA",1_400,"Dev budget qty"),
   ("Demo 5,250 MBH boiler & piping (15x6x7, 13,000 lb)",2,"EA",28_000,"Dev budget qty. Rigging-out is the cost"),
   ("Demo (5) steel columns",5,"EA",9_500,"Dev budget qty"),
   ("Caesarstone plant equipment removal & slurry pit remediation",1,"LS",185_000,"Countertop manufacturing leaves silica and resin residue"),
   ("Misc build-out demo, piping, CMU, partitions",SF*0.35,"SF",2,"Dev budget 024100-2 rate"),
   ("Floor trenching for MEP",1,"LS",50_000,"Dev budget 024100-5"),
   ("Debris removal & dumpsters",1,"LS",95_000,""),
 ]),
 ("Sitework",[
   ("New sidewalks around building",1,"LS",40_000,"Dev budget 320000-1"),
   ("Curb cuts & DOT restoration",1,"LS",35_000,""),
   ("Site drainage tie-ins",1,"LS",15_000,""),
 ]),
]),
("100","ROOF LIFT — mandatory, this is the moat",[
 ("Roof lift contract — YOUR QUOTE",[
   ("Separation of roof from perimeter walls",PERI,"LF",0,"IN the quote"),
   ("Hydraulic jacking: towers, sequencing, survey control",1,"LS",0,"IN the quote"),
   ("Column extensions spliced to existing columns",1,"LS",0,"IN the quote"),
   ("Permanent lateral bracing",1,"LS",0,"IN the quote"),
   ("External metal siding enclosure at new band",BAND,"SF",0,"IN the quote"),
   ("Structural drawings & GC coordination",1,"LS",0,"IN the quote"),
   ("ROOF LIFT CONTRACT — lump",1,"LS",3_500_000,"YOUR QUOTE (Eric), midpoint of $3-4M. Sub-lines above show what it buys"),
 ]),
 ("Foundations for the new load path — ASK if in quote",[
   ("New column footings",40,"EA",7_500,"Dev budget 033000-3, QTY 0"),
   ("Excavation at new columns",SF,"SF",6.50,"Dev budget 033000-1, QTY 0"),
   ("Underpinning at existing footings",24,"EA",9_500,"Existing footings take added load from the taller columns"),
   ("Rebar & dowelling into existing slab",1,"LS",78_000,""),
 ]),
 ("Roof-to-wall closure — ASK if in quote",[
   ("Closure flashing at new roof/wall joint",PERI,"LF",145,"The new joint the lift creates"),
   ("Air & vapour barrier continuity",PERI,"LF",42,""),
   ("Sealants & terminations",1,"LS",38_000,""),
 ]),
 ("Envelope completion at the new band",[
   ("Insulation to energy code",BAND,"SF",8.00,"NYC energy code at the new wall area"),
   ("Girts & secondary framing behind siding",BAND,"SF",4.50,"If not in the lifter's siding scope — ASK"),
   ("Interior liner panel / furring",BAND,"SF",6.00,""),
 ]),
 ("Roof reinstatement",[
   ("Roof repair & flashing where disturbed",SF,"SF",6.00,"NOT a re-roof — the membrane rises with the roof"),
   ("New roof drains & leaders at raised level",18,"EA",8_500,"Dev budget 220000-16 rate"),
   ("Roof dunnage for HVAC equipment",8,"LOC",20_000,"Dev budget 055100-8 rate, QTY 0"),
   ("Roof penetrations framing for exhaust",1,"LS",25_000,"Dev budget 055100-9, QTY 0"),
 ]),
 ("Fireproofing on new steel",[
   ("Spray-applied fireproofing, new columns & bracing",1,"LS",180_000,"NYC-required in assembly occupancy. New steel only"),
 ]),
 ("MEP disconnect & reinstatement",[
   ("Disconnect electrical, mechanical, sprinkler at roof line",1,"LS",200_000,"EXCLUDED by the lifter"),
   ("Reconnect & extend electrical risers to new height",1,"LS",165_000,"EXCLUDED by the lifter"),
   ("Extend sprinkler mains & drops to new height",1,"LS",125_000,""),
   ("Extend mechanical ductwork & piping",1,"LS",60_000,""),
 ]),
 ("Fire separation",[
   ("Rated separation between zones, if required",1,"LS",200_000,"EXCLUDED by the lifter, 'if required'"),
 ]),
]),
("200","STAGE — ground-supported, Factory Town method",[
 ("Stage foundations",[
   ("Footings poured into slab",12,"EA",7_500,"No hurricane scope — interior, zero wind load. FT Infinity footers were $826,986 open-air Miami-Dade"),
   ("Slab cutting & patching at footings",12,"EA",2_400,""),
   ("Anchor bolts & embeds",12,"EA",1_850,""),
 ]),
 ("Stage structure & deck",[
   ("Stage structure design & fabrication",1,"LS",720_000,"FT Infinity actual $2,163,275 (Mountain Production) INCLUDED an open-air roof and crowd weather cover this building does not need"),
   ("Structural steel erection",1,"LS",180_000,""),
   ("Stage deck framing & metal deck",STAGE,"SF",22,""),
   ("Stage T&G wood floor",STAGE,"SF",35,"Dev budget 096400-1, QTY 0"),
   ("Stage stairs & access",4,"EA",13_000,"Dev budget 055100-7 rate"),
 ]),
 ("Production towers & mounting structure",[
   ("Black steel mounting structure — YOUR QUOTE",1,"LS",1_000_000,"Ground-supported so nothing hangs from the building. This is what lets the roof stay at 15 lb/SF"),
   ("Access ladders & unistrut at overhead grid",1,"LS",15_000,"Dev budget 055100-15 / 055100-11, QTY 0"),
 ]),
 ("Rigging grid over the crowd — ground-supported lighting towers + spanning steel",[
   ("Tower footings poured into slab",TOWERS,"EA",8_500,"Same detail as the stage footings. Interior, zero wind load — these carry gravity and the grid's own lateral bracing, not a hurricane case"),
   ("Slab cutting & patching at tower bases",TOWERS,"EA",2_400,""),
   ("Anchor bolts, embeds & base plates",TOWERS,"EA",1_850,""),
   ("Lighting / support towers, 45ft lattice, fabricate & deliver",TOWERS,"EA",34_000,"FT Infinity lighting towers were $92,020 for the lot (Mountain Production). These are dearer per tower because they carry a 150ft spanning grid, not just fixtures. 4 per side at 50ft on centre"),
   ("Cross-span trussed girders over the crowd, %dft clear span"%CROWDW,XLF,"LF",310,"THE ANSWER TO THE USER'S ASK. %d girders at %dft on centre spanning the full %dft crowd width. ~6.5 tons each at $6,000/ton fabricated and erected, plus connections, camber, shop drawings and finish"%(XN,XBAY,CROWDW)),
   ("Longitudinal header trusses on the tower lines",HDRLF,"LF",240,"Two header runs, one per side, %dft each. They spread the cross-girder reactions to the towers at 50ft o.c. so no girder lands mid-span"%CROWDD),
   ("Grid erection: crane, riggers, lifts",1,"LS",185_000,"SCHEDULE. Erect this WHILE THE ROOF IS OFF during the lift window and you pick it straight down through the opening. Erect it after the roof closes and you are assembling 74 tons of steel by chain hoist inside a finished room"),
   ("Chain hoists, 1-ton, at grid pick points",HOISTS,"EA",2_850,"%d points on a %dft x %dft grid is roughly one every 25ft x 25ft"%(HOISTS,CROWDW,CROWDD)),
   ("Motor control, distro & festoon",1,"LS",48_000,""),
   ("Load cells & live load monitoring",1,"LS",36_000,"CODE. Rigging over an assembly occupancy — DOB and your insurer will both want the grid instrumented"),
   ("Rigging steel, shackles, span sets, bridles & secondaries",1,"LS",42_000,""),
   ("PE-stamped structural design & DOB filing for the grid",1,"LS",85_000,"CODE. This is a permanent structure carrying live load over the public. It gets filed, not just built"),
   ("Load test & certification",1,"LS",28_000,"CODE"),
   ("Access catwalk on the header lines",HDRLF,"LF",185,"CUTTABLE. Lets you focus and service the grid without a lift on the floor. Drop it and you focus from a genie between load-ins"),
 ]),
 ("Platforms & FOH",[
   ("VIP platforms & decking fabrication",1,"LS",136_000,"FT actual, Mountain Production"),
   ("FOH platform / control position",1,"LS",55_000,"CORRECTED. This line previously carried $92,020, which is actually FT's LIGHTING TOWERS lot (Mountain Production), not a FOH platform. That figure now sits against the towers below where it belongs. A ~600 SF decked and railed control position with cable management is ~$55,000"),
   ("Stage decking",1,"LS",50_468,"FT actual, Kamilla Productions"),
 ]),
 ("Erection labour & equipment",[
   ("Stage build labour",1,"LS",122_716,"FT actual, Island Productions"),
   ("Crane & rigging for erection",1,"LS",45_000,"FT actual, George's Crane"),
   ("Heavy equipment & lifts",1,"LS",24_390,"FT actual, HERC Rentals"),
 ]),
]),
("300","MEZZANINE — ground-up, inside the existing envelope",[
 ("Mezzanine foundations",[
   ("Column footings poured into slab",24,"EA",7_500,"Dev budget 033000-3, QTY 0"),
   ("Slab cutting & patching",24,"EA",2_200,""),
   ("Base plate grouting",1,"LS",15_000,"Dev budget 033000-11, QTY 0"),
 ]),
 ("Mezzanine structure",[
   ("Structural steel framing incl. elevated standing & box seating",140,"TON",6_000,"14,000 SF at 20 lb/SF. Dev budget 055100-4 rate, QTY 0"),
   ("Metal deck",MEZZ,"SF",4.00,"Dev budget 055100-3 rate"),
   ("Concrete deck poured on metal deck",MEZZ,"SF",25,"Dev budget 033000-9, QTY 0. Poured for acoustic separation and dense standing load"),
   ("Fireproofing on mezzanine steel",MEZZ,"SF",5,"Dev budget 078100-2, QTY 0"),
 ]),
 ("Raised premium tier — replaces built boxes",[
   ("Raised deck platform framing, 18in step",5_600,"SF",16,"REPLACES BUILT BOXES. An 18in step is enough to see over a standing row in front — which is what the boxes were buying"),
   ("Deck surface at the raised tier",5_600,"SF",14,""),
   ("Edge guard rail at the tier",200,"LF",275,"CODE — guard at any change in level over 30in; rail here regardless for safety"),
   ("Two shallow steps up plus ADA ramp at one end",1,"LS",38_000,"CODE — accessible route onto the raised tier"),
 ]),
 ("Egress & guarding",[
   ("Egress stairs",3,"FL",30_000,"CODE — count set by the egress calculation, not preference"),
   ("Concrete in-fill on pan stairs",4,"EA",4_000,"Dev budget 033000-10, QTY 0"),
   ("Guard rail at mezzanine edge",PERI*0.54,"LF",275,"CODE — height and load prescribed. Dev budget 055100-13 rate"),
   ("Handrails at stairs",3,"FL",6_500,""),
 ]),
]),

("400","ENVELOPE & INTERIORS",[
 ("Masonry",[
   ("Patch & repair existing masonry wall",9_972,"SF",10,"Dev budget 042000-1 rate & qty"),
   ("New masonry wall at entry lobby",2_022,"SF",28,"Dev budget qty"),
   ("CMU & brick infill at removed windows/doors/grilles",1,"LS",68_000,"Dev budget 042000-3, QTY 0"),
   ("CMU elevator tower at entrance",3_220,"SF",35,"Dev budget 042000 rate & qty"),
   ("CMU elevator tower at stage",2_977,"SF",35,"Dev budget rate & qty"),
   ("CMU at back wall of music hall",6_097,"SF",35,"Dev budget rate & qty"),
   ("Repointing & cleaning existing facade",1,"LS",85_000,"Dev budget 042000-4, QTY 0"),
 ]),
 ("Doors, frames & hardware",[
   ("Single hollow metal doors, non-acoustic",64,"EA",1_800,"Dev budget 081000-1 rate, QTY 0"),
   ("Double hollow metal doors, non-acoustic",22,"PAIR",2_500,"Dev budget 081000-2 rate"),
   ("Acoustic doors at music hall",18,"EA",6_500,"Dev budget 081000-3 rate. Sound lock at every hall opening"),
   ("Acoustic double doors at music hall",10,"PAIR",10_000,"Dev budget 081000-4 rate"),
   ("Special doors (Eliason)",2,"EA",3_000,"Dev budget 083000-1, priced in file"),
   ("Door hardware, closers, panic devices",96,"EA",950,"CODE — panic hardware on egress doors"),
   ("Install doors/frames/hardware",96,"EA",650,"Dev budget 092000-7 rate"),
 ]),
 ("Storefront & glazing",[
   ("New storefront with doors at entry",900,"SF",250,"Dev budget 084100-1 rate, QTY 0"),
   ("Ballistic box office window",1,"LOT",10_000,"Dev budget 088000-5"),
   ("Mirrors at public restrooms & green rooms",1,"LOT",22_000,"Dev budget 088000-2/3"),
   ("Mirror behind bars",1,"LOT",35_000,"Dev budget 088000-4"),
 ]),
 ("Drywall & partitions",[
   ("Perimeter wall partition at existing exterior wall",9_972,"SF",12,"Dev budget 092000-1 rate & qty"),
   ("Perimeter partition at new exterior wall",2_022,"SF",12,"Dev budget qty"),
   ("2HR fire-rated wall rear of stage, 20ft high",5_565,"SF",20,"Dev budget qty. CODE"),
   ("2HR fire-rated wall rear of music hall, 20ft high",2_857,"SF",20,"Dev budget qty. CODE"),
   ("Plywood 8ft AFF at stage walls",1_672,"SF",9,"Dev budget qty"),
   ("2in insulation above 8ft AFF to 38ft AFF",6_932,"SF",6,"Dev budget qty"),
   ("Proscenium wall",4_194,"SF",22,"Dev budget qty"),
   ("Interior sound/fire rated walls at stairs & shafts",18_000,"SF",20,"Dev budget 092000-3 rate, QTY 0"),
   ("Interior non-rated partitions, BOH & offices",14_000,"SF",12,"Dev budget 092000-4 rate, QTY 0"),
   ("Blocking",1,"LS",30_000,"Dev budget 092000-8"),
 ]),
 ("Acoustic treatment — licence to operate",[
   ("Acoustic panels at music hall walls",28_000,"SF",40,"Dev budget 100500-1 rate, QTY 0. The comparable venue died partly of noise"),
   ("K13 at underside of mezzanine & hall ceilings",42_000,"SF",12,"Dev budget 100500-2 rate, QTY 0"),
   ("Isolation hangers & resilient mounts",1,"LS",145_000,"Structure-borne isolation"),
   ("Acoustic sealant & flanking control",1,"LS",95_000,""),
 ]),
 ("Finishes",[
   ("Tile at restroom floors & walls",6_200,"SF",30,"Dev budget 092300-1/2 rate, QTY 0"),
   ("Sealed & polished concrete elsewhere",52_000,"SF",8,"Dev budget 033000-12 rate. The Infinity aesthetic"),
   ("LVT at green rooms & dressing rooms",3_200,"SF",10,"Dev budget 096000-2 rate"),
   ("Paint walls, doors, ceilings, exposed structure",80_000,"SF",2.50,"Dev budget 099000-1 rate, QTY 0"),
   ("Entry mats & stair treads",1,"LS",32_500,"Dev budget 096000-6/7"),
 ]),
 ("Specialties",[
   ("Toilet partitions",60,"EA",1_500,"Dev budget 100000-3 rate, QTY 0"),
   ("Toilet accessories",30,"SET",7_500,"Dev budget 100000-2 rate"),
   ("Fire extinguishers & cabinets",45,"EA",350,"Dev budget 100000-1 rate. CODE"),
 ]),
 ("Millwork",[
   ("Bar & back bar, six bars",380,"LF",900,"Dev budget 064000 rate, QTY 0"),
   ("Decorative feature above each back bar",6,"EA",10_000,"Dev budget 064000-9"),
   ("Box office millwork",40,"LF",500,"Dev budget 064000-18 rate"),
   ("Merchandise millwork",1,"LS",12_000,"Dev budget 064000-12"),
   ("Public restroom countertops",120,"LF",400,"Dev budget 064000-11 rate"),
   ("Green room bathrooms & countertops",60,"LF",350,"Dev budget 064000-10 rate"),
   ("Coat check shelf & pole",50,"LF",150,"Dev budget 064000-14 rate"),
 ]),
 ("Signage & wayfinding",[
   ("Interior wayfinding & ADA signage",1,"LS",100_000,"CODE — egress and ADA portions"),
   ("Interior door signs & directional",1,"LOT",25_000,"Dev budget 101400"),
 ]),
 ("Rough carpentry & protection",[
   ("Safety protection at roof cut-out",1,"LS",35_000,"Dev budget 062000-1"),
   ("Safety protection at footing trenches",1,"LS",30_000,"Dev budget 062000-2"),
   ("Safety at new mezzanine build-outs",MEZZ,"SF",2,"Dev budget 062000-4 rate"),
   ("Rough carpentry at stage area",STAGE,"SF",5,"Dev budget 062000-5 rate"),
   ("Diamond plate at loading dock walls",1,"LS",18_000,"Dev budget 092000-10"),
 ]),
]),
("500","MEP",[
 ("HVAC",[
   ("Air handling & distribution",SF,"SF",26,"CORRECTED to the 74,100 SF basis. Filed at 120,000 SF x $40"),
   ("Chiller plant, 400-500 ton",450,"TON",3_100,"People alone are ~250 tons at 7,440 occupants"),
   ("Ductwork, diffusers, VAV",SF,"SF",9.50,""),
   ("Building management system",1,"LS",500_000,"Dev budget 230000-2, priced in file"),
   ("Toilet & BOH exhaust",1,"LS",95_000,"WAS 'Kitchen & toilet exhaust' at $165,000. Kitchen exhaust moved to division 800 so the kitchen toggle actually controls every kitchen dollar. Toilet and BOH exhaust stay here because you need them whatever you do about food"),
   ("Smoke control / exhaust at the hall",1,"LS",420_000,"CODE — large-volume assembly space"),
   ("Testing, adjusting & balancing",1,"LS",95_000,""),
 ]),
 ("Heating",[
   ("Radiant tube / panel heating at height",SF,"SF",11,"No heating scope in the dev budget at all. Forced air fails at a 50ft ceiling"),
 ]),
 ("Fire protection",[
   ("Rework existing sprinkler, first floor",69_000,"SF",7,"Dev budget 210000-1 rate & qty"),
   ("New sprinkler & mains at mezzanine",MEZZ,"SF",10,"Dev budget 210000-2 rate"),
   ("Standpipe & booster pump",1,"LS",185_000,"Dev budget 260000 references a standpipe booster pump"),
   ("Fire pump & controller",1,"LS",145_000,"CODE at this height and area"),
   ("Safe-off / disconnect",1,"LS",10_000,"Dev budget 210000, priced in file"),
 ]),
 ("Fire alarm & detection",[
   ("Fire alarm system",88_100,"SF",2.50,"Dev budget 283100-1 rate, corrected to 88,100 SF protected floor"),
   ("Vesda aspirating detection, music hall",1,"LS",150_000,"Dev budget 283100-2, priced in file"),
   ("FDNY filing, inspection & TCO affidavit",1,"LS",35_000,"Dev budget soft cost 209"),
 ]),
 ("Plumbing",[
   ("Water closets",60,"EA",5_500,"Dev budget 220000-2, priced in file. CODE fixture count"),
   ("Lavatories",78,"EA",5_500,"Dev budget 220000-3"),
   ("Urinals",51,"EA",5_500,"Dev budget 220000-4"),
   ("Showers",6,"EA",7_500,"Dev budget 220000-5"),
   ("Green room sinks",6,"EA",5_500,"Dev budget 220000-6"),
   ("Floor drains & sinks",40,"EA",3_500,"Dev budget 220000-8"),
   ("Electric water heaters",10,"EA",7_500,"Dev budget 220000-9"),
   ("Bar roughing, six bars",6,"EA",44_167,"Dev budget 220000-11/12/13 rates, QTY 0"),
   ("Gas piping to equipment",1,"LS",55_000,"Dev budget 220000-18"),
   ("Firestopping",1,"LS",15_000,"Dev budget 220000-20"),
   ("Water service upgrade & backflow",1,"LS",90_000,"Domestic and fire demand at 7,440 occupants"),
 ]),
 ("Electrical service & distribution",[
   ("(2) 2,500A switchboards",2,"EA",195_000,"Dev budget 260000, priced in file"),
   ("Con Ed vault, conduit & feeders from street",1,"LS",850_000,"Dev budget carries only the $50k Con Ed fee"),
   ("Transformer, CT cabinet, metering",1,"LS",325_000,"Dev budget 260000-13, QTY 0"),
   ("Combine existing services",1,"LS",200_000,"Dev budget 260000-13, QTY 0"),
   ("Panels & secondary distribution",1,"LS",480_000,"Dev budget 260000-16, QTY 0"),
   ("General power, devices, floor boxes",SF,"SF",3,"Dev budget 260000-7 rate, QTY 0"),
   ("Power to mechanical equipment, VAVs, exhaust fans",1,"LS",295_000,"Dev budget 260000-10/11/12, QTY 0"),
   ("Dedicated circuits at bar & F&B equipment",1,"LS",165_000,"Dev budget 260000-8 rate"),
   ("Emergency power & inverter package",1,"LS",245_000,"CODE — egress lighting and life safety"),
   ("Generator for fire pump backup",1,"LS",185_000,"Dev budget 260000-15, QTY 0"),
   ("Temporary light & power for construction",125_000,"SF",1.25,"Dev budget 260000-16, priced in file"),
   ("Firestopping at cores & penetrations",1,"LS",12_500,"Dev budget 260000-18, priced in file"),
 ]),
 ("Production power",[
   ("Company switches & cam-lok tie-ins at stage",1,"LS",320_000,"Underwriting carried $1.5M for production power; dev budget nothing"),
   ("Production distro & feeder runs",1,"LS",285_000,""),
   ("Dedicated power to stage equipment",STAGE,"SF",15,"Dev budget 260000-9 rate, QTY 0"),
   ("Isolated technical ground",1,"LS",85_000,"Audio system requirement"),
 ]),
 ("Lighting & controls",[
   ("Exit signs & BOH fixtures",1,"LS",40_000,"Dev budget 265000-1, priced in file. CODE"),
   ("Emergency lighting package",SF,"SF",1,"Dev budget 260000-1 rate, QTY 0. CODE"),
   ("House / architectural lighting, back of house & circulation",1,"LS",185_000,"Not the $1.75M exterior package"),
 ]),
 ("Low voltage",[
   ("Structured cabling backbone & horizontal",1,"LS",245_000,"Dev budget 270000 light for this size"),
   ("CCTV camera wiring",110,"EA",750,"Dev budget 270000-1, priced in file"),
   ("AV wiring infrastructure",1,"LS",60_000,"Dev budget 270000-3"),
   ("Phone & data wiring",1,"LS",45_000,"Dev budget 270000-4"),
   ("Door intrusion & access control wiring",24,"LOC",5_000,"Dev budget 270000-2 rate, QTY 0"),
 ]),
 ("Conveying",[
   ("ADA passenger elevator, two stops",1,"EA",240_000,"CODE — accessible route to every public level"),
   ("BOH / production lift",1,"EA",60_000,""),
 ]),
]),
("600","FF&E",[
 ("Production — audio",[
   ("House PA: mains, subs, fills, amplification, processing",1,"LS",1_850_000,"Always house — artists do not tour a PA for this size room. MT I61/I301: $2-2.2M for L-Acoustics"),
   ("System design, tuning & commissioning",1,"LS",145_000,""),
   ("Rigging, flying hardware & install",1,"LS",205_000,""),
 ]),
 ("Production — lighting",[
   ("House rig: fixtures, truss, hoists",1,"LS",230_000,"REDUCED. FT Infinity house rig actual was ~$205k for an open-air stage: 48x Chauvet Colorstrike M $118,616 (LPS) + rope + pixel bars. $230k for a larger enclosed room"),
   ("Control, dimming & data distribution",1,"LS",85_000,""),
   ("Install & focus",1,"LS",25_000,""),
 ]),
 ("Production — video & soft goods",[
   ("Music hall projector & screen",1,"LS",75_000,"Dev budget FF&E 309"),
   ("Soft goods: stage & perimeter drape",1,"LS",220_000,"REDUCED. Dev budget carried $200,000; the FT benchmark note on the same row said $725k. Working minimum at $220k"),
 ]),
 ("Production — equipment",[
   ("Stage barricade",1,"LS",18_000,"FT actual"),
   ("Dock plates, ramps, hand carts, dollies",1,"LS",30_000,"FT actual"),
   ("Risers",1,"LS",12_000,"FT actual"),
   ("Storage shelving & tools",1,"LS",13_500,"FT actual"),
 ]),
 ("Bar & F&B equipment",[
   ("Bar equipment, six bars, ~53 POS positions",53,"POS",9_000,"CORRECTED. FT and dev budget rate for bar equipment ALONE is $9,000/position. I had used Brooklyn Paramount's $32,192/POS which is ALL-IN incl. kitchen, walk-in and freight — while also carrying those separately below. Double count removed, $689,000"),
   ("Ice machines",4,"EA",15_000,"FT actual rate"),
   ("Walk-in coolers",2,"EA",15_000,"FT actual rate"),
   ("Draft systems & glycol",6,"EA",18_000,"Often vendor-supplied against a pouring agreement — ASK"),
   ("Freight & installation",1,"LS",375_000,"FT / dev budget actual"),
   ("POS terminals",53,"EA",0,"ZEROED per MT I50: \"I can get someone to give it to us for free for using the venue.\" Restore at $3,000/EA if that deal does not land"),
 ]),
 ("Seating — licensing dependency",[
   ("Removable theatre seating, mezzanine",720,"EA","=SEATRATE","TOGGLE. Rate is driven by the seating input cell at the top of this sheet — switch between $25 (MT H127 sourcing) and $125 (as filed in the dev budget). COUNT TO BE CONFIRMED BY COUNSEL — it carries the classification"),
   ("Mezzanine raised-deck seating: stools, high-tops, rail perches",1,"LS",45_000,"REPLACES 657 BOX CHAIRS AT $300 ($197,100). Loose seating on a stepped deck rather than fixed box furniture — flexes between standing and seated nights and holds more people in the same footprint"),
   ("Seat & row numbering, aisle marking",1,"LS",13_760,"Required with removable seating"),
   ("Seating storage racks & carts",1,"LS",35_000,"Stacked away on standing nights"),
 ]),
 ("Furniture",[
   ("Dressing room furniture",6,"EA",10_000,"Dev budget FF&E 301, priced in file"),
   ("Crew & artist lounge",1,"LS",25_000,"Dev budget FF&E 301"),
   ("Office furniture, administration & production",1,"LS",65_000,"Dev budget FF&E 304"),
   ("Merchandise cases",1,"LS",26_000,"Dev budget FF&E 307"),
 ]),
 ("IT, security & operations",[
   ("VoIP, data switching & WiFi",1,"LS",200_000,"Dev budget FF&E 303"),
   ("CCTV cameras",110,"EA",2_000,"Dev budget FF&E 303, priced in file"),
   ("Walk-through magnetometers",12,"EA",10_000,"FT paid $148,580 for a full OPENGATE system with LTE WiFi (CEIA USA) — 12 lanes at $10k lands in the same place"),
   ("Radios & safes",1,"LS",23_000,"Dev budget FF&E 306"),
   ("Custodial, barricades, bike racks, shop equipment",1,"LS",29_000,"FT unit rates: bike rack $211/each, crash barricade $200.76/ft"),
 ]),
 ("Signage",[
   ("Exterior building signage",1,"LS",150_000,"Identification and wayfinding, not a facade programme"),
 ]),
 ("Installation",[
   ("FF&E installation labour",1,"LS",600_000,"Dev budget 120000, priced in file"),
 ]),
]),
("700","SOFT COSTS",[
 ("Design & engineering",[
   ("Architecture & engineering (Wake)",1,"LS",2_200_000,"Dev budget 203. MEP and structural folded in. FT's architect ran 3.9x its budget — watch this"),
   ("Conceptual & brand development",1,"LS",45_000,"Dev budget 203-1"),
   ("Interior design",1,"LS",90_000,"Dev budget 203-2"),
   ("MEP consultant",1,"LS",30_000,"Dev budget 203-7"),
   ("Lighting design",1,"LS",51_000,"Dev budget 203-8, Bandit"),
   ("LV / AV design",1,"LS",35_000,"Dev budget 203-10"),
   ("Signage & wayfinding design",1,"LS",75_000,"Dev budget 203-11"),
   ("Renderings & reimbursables",1,"LS",80_000,"Dev budget 203-12/13"),
   ("Acoustical engineering & design",1,"LS",200_000,"Designing $2M of treatment. Dev budget carried $15,000 for testing only"),
   ("Structural engineering peer review",1,"LS",65_000,"A roof lift warrants an independent check"),
   ("Civil engineering",1,"LS",10_000,"Dev budget 204"),
   ("Traffic engineering",1,"LS",25_000,"Dev budget 205. MT G45: 'prob more'"),
 ]),
 ("Investigation",[
   ("Geotechnical — 13 borings 50ft deep",1,"LS",150_000,"Dev budget 207. Required for the structural (ST) permit"),
   ("Phase I environmental",1,"LS",45_000,"Dev budget carried $0"),
   ("Phase II environmental & soil sampling",1,"LS",105_000,"1948 industrial site, countertop manufacturer"),
   ("Existing-conditions survey & scan",1,"LS",85_000,"Required before a lift"),
   ("Rooflifters Stage 3 structural analysis",1,"LS",50_000,"Fee credited against the contract if awarded. WORTH $4.9M OF SCOPE CERTAINTY"),
 ]),
 ("Permits & approvals",[
   ("DOB permit & plan review fees",1,"LS",90_000,"Dev budget 209-1"),
   ("Special Projects Program",1,"LS",50_000,"Dev budget 209-2"),
   ("MEP & misc permit fees",1,"LS",10_000,"Dev budget 209-2"),
   ("DOB structural (ST) permit filing & expediting",1,"LS",120_000,"12-18 month approval — the other half of the moat"),
   ("FA consultant, filing & inspection scheduling",1,"LS",35_000,"Dev budget 209-4"),
   ("Fire safety & emergency action plan",1,"LS",21_500,"Dev budget 209-5"),
   ("Fire protection plan & FDNY filing",1,"LS",18_500,"Dev budget 209-6"),
   ("Place of Assembly certificate",1,"LS",25_000,"CODE — required above a low occupant threshold"),
   ("Utility connection fees (Con Ed)",1,"LS",50_000,"Dev budget 210. The fee only"),
 ]),
 ("Legal & licensing",[
   ("SLA liquor licence — application & counsel",1,"LS",120_000,"FT's liquor licence came in at $250,000 against a ZERO budget"),
   ("Cabaret licence / current equivalent",1,"LS",45_000,"VERIFY — NYC repealed the cabaret law in 2017. Confirm what applies today"),
   ("Theater use-classification filing & counsel",1,"LS",55_000,"Carries both licences. Must be established at DOB filing"),
   ("Land use / zoning determination",1,"LS",30_000,"The as-of-right claim needs a written determination"),
 ]),
 ("Project management & control",[
   ("Project management — owner's team (Thomas + consultants)",1,"LS",500_000,"CUT TO $500,000 PER MT. WHO IT GOES TO: OUR OWN development team, not Live Nation. Carried against Thomas as project manager plus the outside consultants he runs. Live Nation is the programming / co-pro partner, NOT the developer — they do not staff this and they do not pay for it. At 1.1% of trade cost this is below the 2-4% norm, so it buys ONE full-time PM and a thin consultant bench, not an owner's-rep firm. Under-resourced owner PM is how change orders get approved unchallenged, so this is the line to watch, not the line to cut again"),
   ("Estimating services",1,"LS",20_000,"Dev budget 213-2"),
   ("Controlled & special inspections",1,"LS",140_000,"Dev budget 212 carried $50,000"),
   ("Builder's risk & GL insurance",1,"LS",385_000,"Not separately carried in the dev budget"),
 ]),
 ("Committed",[
   ("Feasibility & due diligence (spent)",1,"LS",342_000,"Dev budget 202. Already committed"),
 ]),
]),
("800","KITCHEN & FOOD SERVICE — scope toggle at the top of the sheet",[
 ("L0 \u00b7 Base food service \u2014 you need this at ANY scope",[
   ("Concession / grab-and-go service points, build-out",4,"EA",22_000,"Four service points off the lobby and the mezzanine. Needed even if you never cook anything on site"),
   ("Reach-in refrigeration at service points",8,"EA",4_200,""),
   ("Power & water to service points",1,"LS",38_000,""),
   ("Hand sinks & DOH compliance at service points",6,"EA",3_800,"CODE. DOH requires a hand sink within reach of every food-handling station, whatever the food is"),
 ]),
 ("L1 \u00b7 Warming / finishing kitchen \u2014 adds to L0",[
   ("Quarry tile floor & coved base",1_400,"SF",22,"CODE. DOH requires a hard, non-absorbent, coved floor in any food prep area"),
   ("FRP wall panels at prep areas",1_200,"SF",15,"Dev budget 092000-9 rate. MOVED HERE from division 400"),
   ("Washable ceiling",1_400,"SF",9,"CODE"),
   ("Type II exhaust hood, non-grease",20,"LF",1_400,"Type II is the cheap hood. It only works if you are NOT frying, grilling or char-broiling"),
   ("Make-up air unit",1,"LS",42_000,"A hood pulls air out of the room. You have to put it back or the room goes negative and the doors will not open"),
   ("Kitchen exhaust duct, shaft & roof penetration",1,"LS",70_000,"MOVED HERE from division 500"),
   ("Kitchen plumbing rough-in",1,"LS",78_000,"Dev budget 220000-15 was $135,000 for a FULL kitchen at qty 0. Warming scope is less"),
   ("Dedicated power to equipment",1_400,"SF",35,"Dev budget 260000-8 rate, QTY 0"),
   ("Walk-in cooler, kitchen",1,"EA",42_000,"Separate from the two BAR walk-ins already carried in division 600"),
   ("Warming & finishing equipment: combis, holding cabinets, prep",1,"LS",165_000,""),
   ("DOH & DOB kitchen filings",1,"LS",35_000,"CODE. A food service establishment is its own permit track"),
 ]),
 ("L2 \u00b7 Full production kitchen \u2014 adds to L1",[
   ("Floor, wall & ceiling at the larger footprint",1_600,"SF",40,"A production kitchen is roughly 3,000 SF against 1,400 for warming"),
   ("Upgrade Type II to Type I grease hood incl. larger make-up air",1,"LS",118_000,"CODE. The moment you fry, grill or char-broil you need a Type I grease hood. This is the single decision that drives the whole cost"),
   ("Hood fire suppression, wet chemical",1,"LS",34_000,"CODE. Follows the Type I hood, no exceptions. 40 LF at $850"),
   ("Grease interceptor, 1,500 gal, cut into slab",1,"LS",85_000,"CODE. DEP requires it. Cutting it into an existing slab is the expensive part"),
   ("Gas service & piping to equipment",1,"LS",175_000,"Dev budget 220000-18 carried $55,000 of piping at qty 0 and no gas SERVICE at all. If the building has no adequate gas service, National Grid is a separate application with its own lead time"),
   ("Additional dedicated power",1_600,"SF",35,""),
   ("Walk-in freezer",1,"EA",43_000,""),
   ("Production equipment: hot line, cold line, ovens, fryers, dish machine",1,"LS",360_000,"Dev budget 114000 listed this BY OWNER and never priced it"),
   ("Smallwares & opening stock",1,"LS",45_000,""),
   ("Roof platform & grease-duct cleaning access",1,"LS",18_000,"CODE. Grease ducts must be cleanable"),
 ]),
]),
]
