# -*- coding: utf-8 -*-
# who, question, why it is hard to deflect, $ at stake
Q = [
("ESTIMATOR / GENERAL CONTRACTOR", [
 ("The $1,000,000 black steel mounting structure at the stage — does that number include ANY steel spanning out over the crowd, or does it stop at the stage line?",
  "It is a one-line lump sum with no take-off behind it. Either it covers the room or it does not, and he has to say which. We are now carrying a separate $1,363,450 rigging grid over the crowd; if his $1M already reaches out over the floor, one of those two numbers comes out.",
  1_363_450),
 ("Is the new roof steel designed to carry ITSELF ONLY, or have you rated it to carry rigging as well?",
  "The whole logic of the ground-supported grid is that nothing hangs from the building. If he has also rated the roof for rigging load he has bought the same capacity twice. At 74,100 SF the difference between 15 lb/SF and 20 lb/SF is 185 tons of steel.",
  1_110_000),
 ("Can the rigging grid be erected during the roof-off window, picked straight down through the opening?",
  "Erecting 74 tons of steel by chain hoist inside a closed, finished room is a different price from craning it in from above. This is a sequencing decision that has to be made before the roof closes — after that it is not available at any price.",
  185_000),
 ("Roughly two-thirds of your trade schedule carries a unit price against a QUANTITY OF ZERO. When are those quantities going in, and what is your own estimate of the total once they are?",
  "Structural steel is $0 on a project whose scope line reads 'Add Second Level'. Acoustic panels are $0 in a music venue. Millwork, doors, painting, fireproofing, tile — all $0.","the whole estimate"),
 ("Roofing row 193 prices 1,592 SF of pavers at $3,312.50/SF. The lines directly above and below, same product, are $31/SF. Is that an error?",
  "One cell. Marked up through 9% OH&P, 10% contractor contingency and 10% owner contingency.","$6,890,129"),
 ("Your escalation line for Building & Fit-Out is blank. The off-site parking garage carries 5%. Why the difference?",
  "The line exists in your file and was left empty.","$3,591,389"),
 ("Your abatement line is $8,750. Your demolition schedule says 74,000 SF of precast roof, 'abatement by others'. Who is 'others', and what have they quoted?",
  "1948 building. 'By others' is not a scope exclusion the owner gets to keep — someone pays it.","$555,750"),
 ("You price HVAC at $40/SF over 120,000 SF. The building is 74,100 SF. Was this priced from a load calculation or from an area assumption?",
  "The tonnage may well be right. The pricing BASIS is applied to 62% more area than exists.","$1,100,000+"),
 ("Your electrical division is $558,750 and contains two switchboards, temporary power and firestopping. Where are the panels, secondary distribution and branch wiring?",
  "Every distribution line in your file is quantity zero. Nothing can plug in.","$3,400,000+"),
 ("What construction duration are your general conditions priced for?",
  "The only duration stated anywhere in your file is 60 weeks of portable toilets — about 14 months. The underwriting assumes 24.","$1,200,000"),
 ("Your summary carries General Conditions at $2,000,000. Your own hidden General Conditions tab totals $2,082,000. Which is right?",
  "Both numbers are in the file you sent.","$82,000"),
 ("You carry 9% overhead, profit and insurance plus a 10% contractor contingency you keep. Will you go open-book with a shared-savings split on unspent contingency?",
  "A fixed OH&P plus a retained contingency gives you no reason to underspend it.","$2,400,000"),
 ("Committed Costs, Invoices and Change Orders are all zero. Nothing has been bought. What would a competitive three-bid process return against this estimate?",
  "5-10% is normal against a first-pass estimate in this market.","$1,800,000-3,600,000"),
 ("Your Project At-a-Glance and Project Summary tabs are broken with #REF!, the cost report is dated 2023-01-31 and the contingency log says March 2020. Is this built on a template from another project?",
  "It matters because the cost-control apparatus is not actually wired to this job.","governance"),
 ("Your Risk Report is empty and exposure is $0. Where do you carry the pending Phase I, the pending structural and MEP assessment, the pending Certificate of Occupancy and the pending FDNY approval?",
  "Those are the four largest uncertainties on the project and none of them appear in your risk register.","governance"),
 ("Are you pricing union or non-union, and what is the delta?",
  "It is the single biggest unknown in the roof lift and it is not stated anywhere.","$1,500,000+"),
 ("Owner's project management is $520,000 — 1.2% of project cost against a 2-4% norm. Is that a real number or a placeholder?",
  "Under-resourced PM is how change orders get approved without challenge.","$600,000"),
]),
("ARCHITECT  (Wake)", [
 ("Does the theater use-classification require seating on a specific floor, fixed or removable, and at what count?",
  "It carries the liquor licence and the cabaret licence. Everything downstream depends on the answer.","$3,156,738"),
 ("Do we actually need four levels? What does the classification require, as opposed to what the test fit proposes?",
  "Every added level multiplies accessible routes, egress stairs, vertical circulation and fire separation.","$1,800,000-2,000,000"),
 ("What is the EGRESS-driven capacity, as distinct from the area-driven capacity?",
  "Egress caps the room, not floor area. The mezzanine is already egress-capped at 2,240.","capacity"),
 ("Your test fit shows 3,714 seated at 7 SF/occ and 5,200 standing at 5 SF/occ. Does that make the floor 26,000 SF and the mezzanine 14,000 SF?",
  "We derived those areas from your own occupancy loads. Confirm or correct them.","$1,851,016"),
 ("Is the roof-deck, restaurant and VIP-lounge programme a client requirement or a design proposal?",
  "It is priced as though it were a requirement. If it is a proposal it can be deferred or deleted.","$1,300,000+"),
 ("Do your drawings assume a roof LIFT or a roof REPLACEMENT?",
  "The development budget schedules 74,000 SF of precast roof for demolition, which is a replacement. A lift keeps the roof.","$4,947,067"),
 ("What is the filing critical path, and which approval gates the Temporary Certificate of Occupancy?",
  "We need the sequence, not a fee proposal. DOB structural approval alone is 12-18 months.","schedule"),
 ("What fire separation between zones is actually required?",
  "Rooflifters excludes it 'if required'. Nobody has said whether it is.","$200,000"),
 ("Confirm the plumbing fixture calculation. The budget carries 189; the underwriting assumed 100.",
  "It is set by occupant load and occupancy group, so there is a right answer.","$489,500"),
 ("Your fee is $2,200,000 with MEP and structural engineering folded into one line. Can we see the breakdown by discipline?",
  "Factory Town's architect ran 3.9x its approved budget. We would like to see the shape of this one.","$2,200,000"),
 ("Does the acoustic treatment need blanket coverage, or targeted treatment on first-reflection and rear surfaces?",
  "28,000 SF of wall panel at $40/SF is the assumption. It is also the licence-to-operate item, so we will not cut it without you.","$400,000"),
]),
("MECHANICAL ENGINEER", [
 ("What is the calculated cooling load in tons, from a real load calculation?",
  "7,440 occupants alone are roughly 250 tons. We need the number, not a $/SF proxy.","$1,100,000+"),
 ("Do we need a building management system at $500,000, or will simpler controls serve a single-volume assembly space?",
  "A BMS is sized for a building with many zones. This is one big room.","$250,000"),
 ("Is mechanical smoke control required at this volume and height, and what does it cost?",
  "We carry $420,000 as an estimate. It is a code question with a definite answer.","$420,000"),
 ("What is the heating strategy at a 50 ft ceiling, and is radiant the right call?",
  "There is NO heating scope in the contractor's budget at all.","$815,100"),
 ("Does the mezzanine add conditioned volume, or only occupants and air distribution?",
  "It sits inside the existing envelope. It should be a minimal uplift, not a new building.","$638,120"),
]),
("ROOFLIFTERS", [
 ("Is the $3-4M lift-only, or does it include the external siding enclosure?",
  "Your published inclusions list siding. We need it confirmed for this project.","$1,800,000"),
 ("Are new column footings and underpinning inside the price?",
  "We carry $1,087,650 for foundations that may already be yours.","$1,087,650"),
 ("Who owns the roof-to-wall closure and its weatherproofing at the new joint?",
  "We carry $241,643 at $187/LF over 1,089 LF. It may be inside your enclosure scope.","$241,643"),
 ("Is the roof MEMBRANE included, or only the external siding?",
  "Different answers change the number by roughly $2.5M.","$2,593,500"),
 ("Union or non-union basis — and can you price both?",
  "Your rate card says non-union. This is New York.","$1,500,000+"),
 ("What is the quote date and how long is it held?",
  "Your published card is 2022. We are assuming 30-40% escalation and would rather not guess.","$1,000,000"),
 ("Can the existing roof structure take being lifted, and will you carry out the Stage 3 on-site structural analysis?",
  "Your own process says the fee credits against the contract. It decides whether this is a $5.7M lift or a $10.6M replacement.","$4,947,067"),
]),
("LANDLORD  (Eric Cohen)", [
 ("Is the 260-space parking garage our scope or yours?",
  "$2,150,000 appears in the development budget and nowhere in the underwriting.","$2,257,500"),
 ("Will you fund the roof lift as base-building work, or provide a TI allowance against it?",
  "A 30 ft roof raise is a permanent improvement to your building that outlives a 20-year lease.","$7,146,288"),
 ("Is the $7.50/SF NNN a negotiated CAP or an estimate of actual charges?",
  "NYC Class 4 real estate tax alone plausibly runs $19-24/SF on the comps in your own deck.","$926,250/yr"),
 ("What build-period base rent abatement is available?",
  "Rent runs through a 12-18 month DOB approval we do not control, before a ticket is sold.","$9,000,000+"),
 ("Is there a renewal option at a pre-agreed rate, and a purchase option at a struck price?",
  "We are funding $45M+ of improvement on your building with no residual at year 20.","structural"),
 ("Will you commit unconditionally, and within a stated time limit, to signing DOB filings as owner of record?",
  "Every filing needs your signature. A promise to be reasonable is not a term.","schedule"),
]),
("COUNSEL", [
 ("Is this use as-of-right in M3-1 — and can we have the written determination with citations?",
  "The underwriting asserts it in one line. It is the largest binary risk in the deal.","the deal"),
 ("Does the mixed programme — venue plus restaurant plus rooftop assembly — create more than one use determination?",
  "The weakest one governs.","the deal"),
 ("What does the theater classification require physically: seat count, fixed vs removable, which floor?",
  "Every seating number we have is a placeholder until you answer.","$3,156,738"),
 ("Does the cabaret licence still exist? NYC repealed the cabaret law in 2017.",
  "If the team is designing around a repealed licence, that shapes the drawings wrongly.","design"),
 ("Does taking the IDA / ICAP sales-tax exemption trigger prevailing wage?",
  "The exemption is worth $1.1-1.5M. Prevailing wage could cost more than that.","net negative"),
 ("Does our liquor licence class carry a food-service requirement?",
  "We are planning to outsource the kitchen entirely.","$215,000"),
]),
]
